### ISSUE TITLE
Impossible to use `bmake` to build docs [on macOS]

### ISSUE THREAD

**Issue by drj11** [tendra/tendra#101]
Hi again from 64-bit Intel macOS and `brew install bmake`

```
; pwd
/Users/drj/prj/tendra/doc
; bmake
bmake: "/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk" line 18: Malformed conditional (${SUBDIR:Munknown})
bmake: Fatal errors encountered -- cannot continue
bmake: stopped in /Users/drj/prj/tendra/doc
```

`bmake` is mentioned in [the README](https://github.com/tendra/tendra) and `brew install bmake` appears to install this: https://formulae.brew.sh/formula/bmake
which brew claims is "Portable version of NetBSD make(1)

https://www.crufty.net/help/sjg/bmake.html"

**Comment by katef** [comment]
hmm. could you also try this please?
https://formulae.brew.sh/formula/bsdmake

It'd hard for me to debug this without access to macos myself

**Comment by drj11** [comment]
```
; bsdmake
"/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk", line 18: Malformed conditional (${SUBDIR:Munknown})
"/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk", line 20: warning: duplicate script for target ".BEGIN" ignored
"/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk", line 21: warning: duplicate script for target ".BEGIN" ignored
"/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk", line 22: warning: duplicate script for target ".BEGIN" ignored
"/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk", line 50: if-less endif
bsdmake: fatal errors encountered -- cannot continue
```

It is hard for me to debug because there is a lot of BSD Make syntax that i'm not familiar with.

**Comment by katef** [comment]
I feel I should point out that macos isn't a supported system, but that shouldn't be for this reason!

**Comment by drj11** [comment]
sure, but i have (or had!) motivation to see what i can do to get macOS working/supported.

**Comment by drj11** [comment]
So I recompiled `bmake` from source, which was also a pain (the case-sensitive file system messes up the standard build, and the suggested workaround appears to make a working executable but bmake's install scripts refuse to install because some of the tests don't pass because the workaround is to build in a different directory and some of the tests have the directory names in their expected output), but...

I get the same error as in the opening comment.

How are you magically using a version of BSD make that supports variable modifiers in a `.if`?

**Comment by katef** [comment]
Here's what I'm using:
```
; dpkg -l | grep bmake
ii  bmake                                    20200710-15                                amd64        NetBSD make
```

I think the problem here must be unrelated to the bmake version.

Can you try both:
`bmake -r`
and adding:
```
.BEGIN:
    @${ECHO} 'XXX $${SUBDIR}'
```
(that's a tab)
just before that line please?

**Comment by drj11** [comment]
```
; bmake -r
bmake: "/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk" line 19: warning: duplicate script for target ".BEGIN" ignored
bmake: "/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk" line 15: warning: using previous script for ".BEGIN" defined here
bmake: "/Users/drj/prj/tendra/doc/shared/mk/tendra.subdir.mk" line 21: Malformed conditional (${SUBDIR:Munknown})
bmake: Fatal errors encountered -- cannot continue
bmake: stopped in /Users/drj/prj/tendra/doc
; git diff
diff --git a/shared/mk/tendra.subdir.mk b/shared/mk/tendra.subdir.mk
index 362c74e0b..6a319c6a0 100644
--- a/shared/mk/tendra.subdir.mk
+++ b/shared/mk/tendra.subdir.mk
@@ -15,6 +15,9 @@ _TENDRA_SUBDIR_MK_=1
        @${EXIT} 1;
 .endif
 
+.BEGIN:
+       @${ECHO} 'XXX $${SUBDIR}'
+
 .if ${SUBDIR:Munknown}
 .BEGIN:
        @${ECHO} '$${SUBDIR} contains "unknown"; possibly you have an unsupported system.'
```

I'm gonna keep hacking to try and discover the value of `${SUBDIR}` (which we should expect to match the `unknown` pattern, right?)

**Comment by drj11** [comment]
When `${SUBDIR}` is not set, the make script failure is opaque. I edited `shared/mk/tendra.subdir.mk` to comment out the whole `.if ${SUBDIR:Munknown}` section. Now I get:

```
; bmake -r
${SUBDIR} must be set
*** Error code 1

Stop.
bmake: stopped in /Users/drj/prj/tendra/doc
; git diff
diff --git a/shared/mk/tendra.subdir.mk b/shared/mk/tendra.subdir.mk
index 362c74e0b..8c39b7705 100644
--- a/shared/mk/tendra.subdir.mk
+++ b/shared/mk/tendra.subdir.mk
@@ -15,12 +15,12 @@ _TENDRA_SUBDIR_MK_=1
        @${EXIT} 1;
 .endif
 
-.if ${SUBDIR:Munknown}
-.BEGIN:
-       @${ECHO} '$${SUBDIR} contains "unknown"; possibly you have an unsupported system.'
-       @${ECHO} 'See shared/mk/tendra.makedefs.mk for supported systems.'
-       @${EXIT} 1;
-.endif
+#.if ${SUBDIR:Munknown}
+#.BEGIN:
+#      @${ECHO} '$${SUBDIR} contains "unknown"; possibly you have an unsupported system.'
+#      @${ECHO} 'See shared/mk/tendra.makedefs.mk for supported systems.'
+#      @${EXIT} 1;
+#.endif
 
 .for entry in ${SUBDIR}
 . if !exists(${.CURDIR}/${entry})
```

At least `${SUBDIR} must be set` is clear on the _what_ if not the _how_ or _why_.

**Comment by drj11** [comment]
is `SUBDIR` not set because i am running from within the `/doc` directory?

it seems sensible that it be possible to build the documentation without building the compiler, but is this the right way to do that?

**Comment by katef** [comment]
I think building from within /doc should work, yes. But it's possible that we're missing some build system stuff for it. I did my best to keep that working when I was cutting up repositories and migrating things around a while ago, but I'm not sure at the moment.

**Comment by katef** [comment]
oh! sorry, I forgot about that! That's because the docs build brings in more dependencies, and people had complained about needing those when they just wanted to build the compiler. So I made it optional.

**Comment by drj11** [comment]
Sure makes sense. I too would feel awkward if i needed `xsltproc` to build a compiler.

Is it possible to get `bmake -r` working if it is run directly in `/doc` ? With some `bmake` magic?

**Comment by drj11** [comment]
If you want it, PR #110, adds this magic ability to build the docs with `bmake -r` from within the `/doc` directory.
