### ISSUE TITLE
building doc unclear and/or doesn't work

### ISSUE THREAD

**Issue by drj11** [tendra/tendra#112]
Did the contents of `/doc/` used to be in `/trans/doc/`?

`/trans/doc/` exists but has no `Makefile`, only what appear to be some copyright relicts.

Which means that a top-level `bmake -r build-doc` fails on the _trans_ project:

```
; bmake -r build-doc
===> building documents
cd /Users/drj/prj/tendra/calculus/doc && bmake  -DDEVELOPER OBJ_DIR=/Users/drj/prj/tendra/obj.ariane-doc/calculus
cd /Users/drj/prj/tendra/trans/doc && bmake  -DDEVELOPER OBJ_DIR=/Users/drj/prj/tendra/obj.ariane-doc/trans
bmake[1]: no target to make.

bmake[1]: stopped in /Users/drj/prj/tendra/trans/doc
*** Error code 2

Stop.
bmake: stopped in /Users/drj/prj/tendra
```
(an earlier run of the command has already built `calculus/doc`.

I see the `XXX: just temporary` in the Makefile so this might all be irrelevant.

**Comment by katef** [comment]
No; `trans/doc` is for documentation specific to trans, other than the manpages. (There isn't any, aside from the copyright stuff you saw there).

Closing this; related discussion on #110.

**Comment by drj11** [comment]
fine, but `bmake -r build-doc` (at top-level) still fails.
