### ISSUE TITLE
Unknown preprocessing directive, '#warning'.

### ISSUE THREAD

**Issue by reznikmm** [tendra/tendra#24]
Since Ubuntu 18.04 `bmake` fails with errors like:

```
/tmp/tendra/obj.untu-bootstrap/bin/tcc -I/tmp/tendra/osdep/machines/glibc/x32_64/include -I/tmp/tendra/osdep/machines/glibc/common/include -Nproxy:/tmp/tendra/osdep -Nsystem:/usr/ic
/usr/include/math.h, line 30: Error:
  [C90 6.8]: Unknown preprocessing directive, '#warning'.

/usr/include/math.h, line 31: Error:
  [C90 6.8]: Unknown preprocessing directive, '#warning'.

*** Error code 1

Stop.
bmake[5]: stopped in /tmp/tendra/osdep/machines/glibc/common/api
*** Error code 1
```

The simplest reproducer is:
```
cat >aaa.c <<EOF
> #if 0
> #warning Text
> #endif
> EOF
$ tcc aaa.c
aaa.c, line 2: Error:
  [C90 6.8]: Unknown preprocessing directive, '#warning'.
```

I would propose implement this directive or don't raise an error for this particular preprocessing directive inside excluded blocks of code.

**Comment by katef** [comment]
Thanks! Warning is non-standard, but we do have a pragma to allow it. See e.g.:
https://github.com/tendra/tendra/blob/main/osdep/machines/openbsd/common/include/stdlib.h#L7

**Comment by katef** [comment]
Perhaps we should provide that under one of the -X modes for tcc. I'm not sure which

**Comment by FFY00** [comment]
Hey!

I am pretty sure this is happening because tendra is not correctly detecting your libc. The glibc identification routine was broken on some systems, #34 might have fixed it for you. Could you try building `main`?

If it still doesn't work, your specific glibc version might not be supported yet, or maybe you have a weird version string. In that case, could you post the output of `ldd --version`.

**Comment by katef** [comment]
Added for glibc 2.27 in f0ac84b04.

**Comment by katef** [comment]
Confirmed, this is resolved now :)

**Comment by ennorehling** [comment]
I'm seeing similar problems trying to build on Debian Stretch, with glibc 2.24:
```
==> Compiling c89.api/alloc.c
/home/enno/src/tendra/obj.erdbaer-bootstrap/bin/tcc -I/home/enno/src/tendra/osdep/machines/glibc/x32_64/include -I/home/enno/src/tendra/osdep/machines/glibc/common/include -Nproxy:/home/enno/src/tendra/osdep -Nsystem:/usr/include   -D_unknown -D_ARCH_x32_64 -Y32bit -D__BUILDING_LIBS -f/home/enno/src/tendra/osdep/machines/glibc/common/api/c89.h -f/home/enno/src/tendra/obj.erdbaer-bootstrap/share/tspec/TenDRA/feature/c89.h -f/home/enno/src/tendra/osdep/machines/glibc/common/startup/c89.h  -Ymakelib -Yposix  -o /home/enno/src/tendra/obj.erdbaer-bootstrap/obj/osdep/machines/glibc/common/api/apis/c89.api/alloc.j /home/enno/src/tendra/obj.erdbaer-bootstrap/share/tspec/TenDRA/src/c89.api/alloc.c
/usr/include/features.h, line 148: Error:
  [C90 6.8]: Unknown preprocessing directive, '#warning'.

/usr/include/features.h, line 364: Error:
  [C90 6.8.2]: Can't open included file, 'sys/cdefs.h'.

/usr/include/features.h, line 388: Error:
  [C90 6.8.2]: Can't open included file, 'gnu/stubs.h'.

/usr/include/stdlib.h, line 41: Error:
  [C90 6.8.2]: Can't open included file, 'bits/waitflags.h'.

/usr/include/stdlib.h, line 42: Error:
  [C90 6.8.2]: Can't open included file, 'bits/waitstatus.h'.

/usr/include/stdlib.h, line 56: Error:
  [C90 6.5.2]: The type '__BEGIN_DECLS' hasn't been declared.

/usr/include/stdlib.h, line 58: Error:
  [Syntax]: Parse error before 'typedef'.
  [Syntax]: Can't recover from this error.

*** Error code 1
```

**Comment by FFY00** [comment]
Hi :blush:

glibc is not supported yet, can you open a different issue? Thanks!

**Comment by katef** [comment]
Hi @ennorehling! The way libc stuff is supported is done per version. We do have glibc support, but not for 2.24 specifically.

Adding new versions is fairly straightforward. Usually it's just a case of copying what's there already for similar versions.

If you `grep -r _GLIBC2_ osdep/` you can see how that's done. Try cut & pasting those, and see how far you get? (And add 2.24 to shared/mk/tendra.makedefs.mk too).

I can help out if you need me :)

**Comment by katef** [comment]
Similar diff for https://github.com/tendra/tendra/pull/41 if it helps to look at that, too.
