### ISSUE TITLE
www.tendra.org is down

### ISSUE THREAD

**Issue by henrik242** [tendra/tendra#25]
☝️

**Comment by katef** [comment]
Yes, sorry about that. I'll try to get it back up in a few days. You're not missing anything that isn't on github though.

**Comment by katef** [comment]
This should be back up now: http://www.tendra.org/
I hope. It's a bit hard for me to test properly, I have a terrible connection here.

**Comment by henrik242** [comment]
It's up! 👍👍  My thoughts and prayers go out to your terrible connection.
