### ISSUE TITLE
C99: single line comments

### ISSUE THREAD

**Issue by partouf** [tendra/tendra#33]
Compiler-explorer has a default example for when you select a language:
```
// Type your code here, or load an example.
int square(int num) {
    return num * num;
}
```

But the `// comment` is not implemented, so by default there's always an error until the user removes the comment.

Most, if not all, compilers have supported single line comments way before C99, I think.

Are there any options or defines you want to use to switch on C99 features, or can this be added regardless?

/me currently struggling through all the things to find out how to add support for this

**Comment by partouf** [comment]
Actually I'm not sure I can actually figure this out on my own

**Comment by FFY00** [comment]
`gcc -std=c89`/`gcc -ansi` doesn't support this IIRC. I don't think a define should be used to switch to C99 features, a CLI switch would be my preferred option. If we add a switch, we have to make it default in compiler-explorer too. Anyway, just my 2 cents :blush:

**Comment by FFY00** [comment]
I am not convinced we have a problem right now, we just need to get C99 implemented. We can implement start implementing such features and allow them by default.

**Comment by katef** [comment]
Right, these are introduced by C99. We only provide C90.

But a lot of the C frontend is controlled by options - everything like this is set by tcc's modes. There's a start on C99, for example: https://github.com/tendra/tendra/blob/main/tcc/startup/lang/c99.h#L22

The C frontend shares its guts with C++, so we do already have internal support for some of the C99 things that overlap with C++. `//` comments are one of those. The option is called `cpplus_comment`, you can enable it by:
```
#pragma TenDRA option "cpplus_comment" allow
```

The repo here is actually what used to be two (long abandoned) forks, and we've merged them all. My plan is to cherry-pick all the good stuff, and make sure of the good work people did there. Especially by Stefan.

Stefan did this already, for tcc's WIP C99 mode, on the ten15.org branch. So we can cherry-pick this: c405aaf3113f415f771bcf0409327d3d4392f4b9 
This goes in tcc/startup/lang/c99.h

Easy :)

**Comment by katef** [comment]
You invoke these modes by like `tcc -Yc99 ...`

**Comment by katef** [comment]
Apparently you don't invoke those modes like that, because `-Yc99` only brings in the C99 API, not the tcc/startup/lang/{c89,c99}.h language stuff. I'll see if I can add something to control that.

**Comment by katef** [comment]
I think we can do something like this in the tcc env files:
```diff
-+STARTUP               "-f<PREFIX_STARTUP>/lang/c89.h"
++STARTUP               "-f<PREFIX_STARTUP>/<LANG>/c89.h"
```

And then set `LANG` differently for `-Yc99` vs. the others.

**Comment by katef** [comment]
Oh! I already had the same idea. haha
https://github.com/tendra/tendra/issues/18

**Comment by partouf** [comment]
hmm, I fetched these changes and tried `tcc -Yc99 main.c` on a file with //-comments, but it still gives an error

**Comment by katef** [comment]
Right, that's because we don't have an interface to invoke C99 yet (which is what #18 is for).

Are you intending to expose that in CE? If you want to present a non-standard mix of features, it might make sense to keep your own set of pragmas for whatever non-standard things your code examples use.

You can prepend a header (without affecting line numbers) like this:
```
; cat abc.c 
// hello
int main(void) { return 0; }
; ./obj.when-bootstrap/bin/tcc abc.c
abc.c, line 1: Error:
  [Syntax]: Parse error before '/'.
  [Syntax]: Can't recover from this error.

;                                   
; cat x.h 
#pragma TenDRA option "cpplus_comment" allow
; ./obj.when-bootstrap/bin/tcc -f x.h abc.c
; 
```

(where x.h would be whatever settings suit CE)

TenDRA is pretty strict about standards compliance, and I don't want to mislead people by calling something C99 when really we're only just starting on that. Especially because it quotes the C standards in its error messages, but C89/C90 does not allow these single-line comments.

**Comment by partouf** [comment]
I don't think we want to do something that isn't reproducible locally for users, that would be bad for both sides of the coin.
So I think I'll just close this issue and we'll see it whenever a more complete C99 implementation is available.
