### ISSUE TITLE
In tcc, exit is called from function registered to atexit

### ISSUE THREAD

**Issue by pascal-cuoq** [tendra/tendra#40]
The Linux man page for `atexit` notes that (https://www.man7.org/linux/man-pages/man3/atexit.3.html ):

> POSIX.1  says that the result of calling exit(3) more than once (i.e., calling exit(3) within a function registered using atexit()) is undefined.  On some systems (but not Linux), this can result in an infinite recursion; portable programs should not invoke exit(3) inside a function registered using atexit().

And indeed, the FreeBSD man page warns that (https://www.freebsd.org/cgi/man.cgi?query=atexit&sektion=3 ):

> These [callback] functions must not call exit()

In the source code at `tcc/src`:

1.  `main_end`, which is registered with `atexit`, calls `cmd_env`: https://github.com/tendra/tendra/blob/736d5fbc288fb86ed931c66b1fb502cfdbe13d87/tcc/src/main.c#L63
2. `cmd_env` calls `error`: https://github.com/tendra/tendra/blob/736d5fbc288fb86ed931c66b1fb502cfdbe13d87/tcc/src/execute.c#L171
3. And the `error` function calls `exit`: https://github.com/tendra/tendra/blob/736d5fbc288fb86ed931c66b1fb502cfdbe13d87/shared/src/error.c#L127

I can submit a PR that guards one of the functions on the chain with a boolean variable indicating that the program is already exiting, if:

- you agree that this is a problem worth fixing
- you tell me which function you think it's best to guard.

I would suggest to make `error` call `_exit` instead of `exit` if the boolean variable indicating that we are exiting has been set, and to set this variable first thing in `main_end`.

**Comment by katef** [comment]
Absolutely, a PR would be very welcome, thank you!

Calling `_exit()` instead of `exit()` is surely the right thing to do here, yes.

I don't think I understand what you're suggesting with a boolean though. In `error_msg()`, we already pass the severity, which is used to decide whether to exit or not, on the line you show. Doesn't that serve our purposes here already?

**Comment by pascal-cuoq** [comment]
What I mean about the boolean variable is that `cmd_env` is used in several places in `tcc`, some of them not in `main_end`. If one of those calls fail, we want `cmd_env` to indirectly call `exit`, which will cause `main_end` to be called and clean up temporary files (that seems to be its main function). However, if `tcc` is already exiting, we want to call `_exit`.

The information must be passed somehow to `error` which of the two cases apply (the “if we decide to exit, call `exit`” case and the “if we decide to exit, call `_exit`” case).

One solution is to pass an extra argument to `cmd_env`, which will transmit it to `error`, which will use it to decide. That would be the “functional programming” way. Another solution is to set a static-lifetime boolean variable to true when we enter `main_end`, so that the same `cmd_env`, which is sometimes used in a normal context and sometimes used in an “exiting” context, can call `error_msg` knowing that it will do the right thing for the current context by looking at the variable.

It doesn't feel right to attempt to fix this problem by just tweaking the severity passed to `error_msg` by `cmd_env`, because currently, `cmd_env` does not know if it's called in a normal context or an exiting context. Fixing it this way would result in loss of functionality (namely, temporary files would no longer be deleted when an error in `cmd_env` causes `tcc` to exit).

**Comment by pascal-cuoq** [comment]
I was thinking of a change like this (not tested). While preparing it, I noticed the variable `exit_status`, which **might** be usable for this purpose, although I think currently it is set too late to prevent from calling `exit` while already exiting.
```
diff --git a/shared/include/error.h b/shared/include/error.h
index ddf891836..fd81727f2 100644
--- a/shared/include/error.h
+++ b/shared/include/error.h
@@ -26,6 +26,7 @@ void fmt_register(char c, void (*f)(FILE *fp, void *));
 
 extern const char *progname;
 extern const char *progvers;
+extern int exiting;
 extern int exit_status;
 extern unsigned long maximum_errors;
 extern unsigned long number_errors;
diff --git a/shared/src/error.c b/shared/src/error.c
index 83d9f91ff..dc97aad55 100644
--- a/shared/src/error.c
+++ b/shared/src/error.c
@@ -17,6 +17,7 @@
 const char *progname = NULL;
 const char *progvers = NULL;
 
+int exiting = 0;
 int exit_status = EXIT_SUCCESS;
 unsigned long maximum_errors = 20;
 unsigned long number_errors = 0;
@@ -124,7 +125,10 @@ error_msg(enum error_severity e, const char *fn, int ln, const char *s, va_list
        IGNORE fprintf(stderr, "\n");
 
        if (e == ERR_FATAL || e == ERR_USAGE) {
-               exit(exit_status);
+               if (exiting)
+                       _Exit(exit_status);
+               else
+                       exit(exit_status);
        }
 
        if (number_errors >= maximum_errors && maximum_errors) {
diff --git a/tcc/src/main.c b/tcc/src/main.c
index d0b710b78..2dccc4109 100644
--- a/tcc/src/main.c
+++ b/tcc/src/main.c
@@ -55,6 +55,7 @@ print_version(void)
 static void
 main_end(void)
 {
+       exiting = 1;
        remove_junk();
        remove_startup();
        if (tempdir != NULL &&
```

**Comment by katef** [comment]
Oh I see! Yes, that makes sense.
Thank you :)
