### ISSUE TITLE
Bitmasking Operations Appear to Fail when `builtin` Has > 1 Flag Set

### ISSUE THREAD

**Issue by hawkinsw** [tendra/tendra#95]
https://github.com/tendra/tendra/blob/df9d52a9ad82cbcf4f532cb7f609490b1add2dca/trans/src/common/special/special.c#L94

It _seems_ like the bit manipulation here does not work in the case where `builtin` contains more than one set flag.  

Here's my, probably faulty, reasoning:

Let's say that `builtin` is 11000000t and `a[i].mask` is 10000000t -- in other words, the builtin at `a[i]` is on. `a[i].mask` > 1 => true so we'll continue to evaluate the second half of the condition, the `(builtin & ~a[i].mask)`. We bitwise negate `a[i].mask` and get 01111111t. We bitwise and that with 11000000t and, unfortunately, the result is > 0 => true. As a result, we `continue` past this option when we should really be acting on it. 

I *think* that the fix is simple. Instead of 

```
    if (a[i].mask && (builtin & ~a[i].mask)) {
```

it should be

```
    if (a[i].mask && (~builtin & a[i].mask)) {
```

I have tested this and it appears to _do the right thing_. 

That said, it's late and my eyes are very tired -- I could be totally off! Please correct me where I am wrong or have overstepped my bounds. In the miracle case that it is a typo and the proper fix is above, I will submit an accompanying PR. 

Thanks, as always, for being so welcoming!
Will

**Comment by katef** [comment]
i think you're right, i'd inverted the wrong side of the expression here. thank you!
